spring.application.name=MSCandidat4twin6
spring.cloud.config.import-check.enabled=false
spring.cloud.config.enabled=false
server.port=8081

#h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2


# Datasource
spring.datasource.username=etudiants_user
spring.datasource.password=
#spring.datasource.url=jdbc:h2:file:./Database/Data/Etudiants
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = create

#eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defauktZone=http://localhost:8761/eureka