welcome.message=Welcome to MSClasse4twin6 MS
server.port=8084

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:file:./Database/Data/classes_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=classes_user
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2
